add radgov-ls and radgov account

diff --git a/libexec/radgov/radgov-execute b/libexec/radgov/radgov-execute
--- a/libexec/radgov/radgov-execute
+++ b/libexec/radgov/radgov-execute
@@ -9,5 +9,6 @@ if [[ $(radgov state "$1") != Queued ]]; then
   echo >&2 "Proposal is not Queued, execution will fail"
   exit 1
 fi
+[[ $ETH_FROM ]] || (echo >&2 "${0##*/}: error: Please set ETH_FROM to your account address" && exit 1)
 
-seth send "$RADGOV" "execute(uint256)" "$1"
+seth send "$RADGOV" "execute(uint256)" "$1" --from $ETH_FROM
