add radgov-ls and radgov account

diff --git a/libexec/radgov/radgov b/libexec/radgov/radgov
--- a/libexec/radgov/radgov
+++ b/libexec/radgov/radgov
@@ -128,4 +128,9 @@ if ! [ -x "$(command -v "${0##*/}-${1-help}")" ]; then
     exit 1
 fi
 
+
+[[ $RAD ]] || (echo >&2 "${0##*/}: error: Please set RAD to the address of the Radicle token" && exit 1)
+[[ $RADGOV ]] || (echo >&2 "${0##*/}: error: Please set RAD_GOV to the address of the Radicle Governance contract" && exit 1)
+
+
 "${0##*/}-${1-help}" "${@:2}"
diff --git a/libexec/radgov/radgov-queue b/libexec/radgov/radgov-queue
--- a/libexec/radgov/radgov-queue
+++ b/libexec/radgov/radgov-queue
@@ -10,4 +10,6 @@ if [[ $(radgov state "$1") != Succeeded ]]; then
   exit 1
 fi
 
-seth send "$RADGOV" "queue(uint256)" "$1"
+[[ $ETH_FROM ]] || (echo >&2 "${0##*/}: error: Please set ETH_FROM to your account address" && exit 1)
+
+seth send "$RADGOV" "queue(uint256)" "$1" --from $ETH_FROM
